spring:
  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.visasim.notificationservice.event
        spring.json.value.default.type: com.visasim.notificationservice.event.TransactionCompletedEvent
        spring.json.use.type.headers: false

    listener:
      ack-mode: record
      missing-topics-fatal: false
