services:
  postgres:
    image: postgres:16
    container_name: visasim-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: visasim
      POSTGRES_USER: visasim
      POSTGRES_PASSWORD: visasim_dev_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.8.0
    container_name: visasim-kafka
    restart: unless-stopped

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093

      # IMPORTANT:
      # Containers connect using kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    volumes:
      - kafka_data:/var/lib/kafka/data

  redis:
    image: redis:7.4
    container_name: visasim-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile

    container_name: visasim-user-service
    restart: unless-stopped

    ports:
      - "8081:8081"

    environment:
      # PostgreSQL → Docker service name
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/visasim
      SPRING_DATASOURCE_USERNAME: visasim
      SPRING_DATASOURCE_PASSWORD: visasim_dev_password

      # Kafka → Docker service name
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      # Redis → Docker service name
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      FRAUD_SERVICE_BASE_URL: http://fraud-service:8082

    depends_on:
      - postgres
      - kafka
      - redis

  fraud-service:
    build:
      context: ./fraud-service
    container_name: visasim-fraud-service
    ports:
      - "8082:8082"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://fraud-postgres:5432/visasim_fraud
      SPRING_DATASOURCE_USERNAME: visasim
      SPRING_DATASOURCE_PASSWORD: visasim_dev_password

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      USER_SERVICE_BASE_URL: http://user-service:8081

    depends_on:
      - fraud-postgres
      - redis
      - user-service

  notification-service:
    build:
      context: ./notification-service
    container_name: visasim-notification-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  fraud-postgres:
    image: postgres:16
    container_name: visasim-fraud-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: visasim_fraud
      POSTGRES_USER: visasim
      POSTGRES_PASSWORD: visasim_dev_password
    ports:
      - "5433:5432"
    volumes:
      - fraud_postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: visasim-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - user-service
      - fraud-service
      - notification-service

  grafana:
    image: grafana/grafana:latest
    container_name: visasim-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus

volumes:
  postgres_data:
  kafka_data:
  fraud_postgres_data:
